owner: fastandcomfy 
repo: bug-free-train 

sites:
  - name: Dev API
    url: https://apidev.fastandcomfy.io
    assignees:
      - ecelustka
    __dangerous__disable_verify_peer: true
  - name: Dev Developers
    url: https://developersdev.fastandcomfy.io
    assignees:
      - ecelustka
    __dangerous__disable_verify_peer: true
  - name: Dev Web
    url: https://dev.fastandcomfy.io
    assignees:
      - ecelustka
    __dangerous__disable_verify_peer: true
  - name: Dev Wizard
    url: https://wizarddev.fastandcomfy.io
    assignees:
      - ecelustka
    __dangerous__disable_verify_peer: true
status-website:
  # cname: demo.upptime.js.org
  baseUrl: /bug-free-train
  logoUrl: https://res.cloudinary.com/fastandcomfy/image/upload/w_48,h_48/v1623865779/logo.svg
  name: Fast and Comfy Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
